### ISSUE TITLE
Install on Windows Broken

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#113]
_Original author: nmaior...@gmail.com (May 11, 2012 03:24:03)_

<b>What steps will reproduce the problem?</b>
1. gradelw install
<b>2.</b>
<b>3.</b>

What is the expected output? install completes without failures What do you see instead? Fails to find symbol Clock

C:\javadevelopment\CS373-Robotics-Hackathon\rosjava-core\rosjava\src\main\java\org\ros\time\ClockTopicTimeProvider.java:44: error: cannot find symbol
      public void onNewMessage(Clock message) {
                               ^
  symbol: class Clock

What version of the product are you using? 0.0.0-SNAPSHOT On what operating system? Windows 7

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=113_

**Comment by jubeira** [comment]
Closing. Not applicable on 2019.
