### ISSUE TITLE
Android: java.net.UnknownHostException when subscribing to a custom message.

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#146]
_Original author: jmatas...@gmail.com (September 28, 2012 08:53:21)_

<b>What steps will reproduce the problem?</b>
1. Create a Subscriber to custom message in an Android_tutorial_example.
2. Run it in a tablet.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
It should work as any others subscribers I have in my code. For example &quot;nav_msgs.Odometry&quot; Subscriber. 
When running in the tablet, it produces the next log:

&quot;E/UpdatePublisherRunnable(4793): java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host &quot;arturo-desktop&quot;: No address associated with hostname&quot; 

When I remove this subscriber the log disappear.
<b>What version of the product are you using? On what operating system?</b>
I am using Android 4.0.3 and working in Ubuntu 10.04

<b>Please provide any additional information below.</b>

My custom message is a List of Lists that provide information about the nodes running in the system. It provides a List of NodesInfo composed of Subscribers and Publishers, etc. I include my custom message.
Thanks!

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=146_

**Comment by damonkohler** [comment]
That error has nothing to do with your custom message. Your Android device is unable to resolve the host name (as the error indicates). This is a networking issue.

**Comment by seank-com** [comment]
We have the same issue with one important difference.

```
10-17 12:07:00.732 10173-10305/org.loomo.ros I/DefaultPublisher: Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</LO01/loomo_ros_bridge_node, http://192.168.42.106:33374/>, TopicIdentifier</LO01/base_pitch>>, Topic<TopicIdentifier</LO01/base_pitch>, TopicDescription<std_msgs/Float32, 73fcbf46b49191e672908e50842a83d4>>>>
10-17 12:07:00.733 10173-10315/org.loomo.ros I/DefaultSubscriber: Subscriber registered: Subscriber<Topic<TopicIdentifier</LO01/cmd_vel>, TopicDescription<geometry_msgs/Twist, 9f195f881246fdfa2798d1d3eebca84a>>>
10-17 12:07:00.736 10173-10322/org.loomo.ros I/Registrar: Response<Success, Subscribed to [/LO01/mode], []>
10-17 12:07:00.737 10173-10320/org.loomo.ros I/DefaultSubscriber: Subscriber registered: Subscriber<Topic<TopicIdentifier</LO01/mode>, TopicDescription<std_msgs/Int8, 27ffa0c9c4b8fb8492252bcad9e5c57b>>>
10-17 12:07:00.742 10173-10307/org.loomo.ros E/UpdatePublisherRunnable: java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "ROS": No address associated with hostname
10-17 12:07:00.778 10173-10233/org.loomo.ros D/HeadSubscriber: start_sensor()
10-17 12:07:00.779 10173-10233/org.loomo.ros D/LocomotionSubscriber: node_started
10-17 12:07:00.779 10173-10233/org.loomo.ros D/LocomotionSubscriber: start
```

Our MainActivity (which is inherited from RosActivity) is connected to our ROS master like so

```java
    public MainActivity() { super("LoomoROS", "LoomoROS", URI.create("http://192.168.42.100:11311/")); }
```

Notice, we never mentioned the host name was "ROS", why then do we see this error at all? We provided the ip address there should be no reason to do a DNS lookup.

**Comment by seank-com** [comment]
Doing an ```export ROS_HOSTNAME=192.168.42.100``` in the terminal before running rqt (which we were using to publish cmd_vel messages) worked around the issue.
