### ISSUE TITLE
rosjava-based packages fail to build with Gradle 1.0-milestone-3: "Could not find method maven()"

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#149]
_Original author: martin.g...@gmail.com (October 30, 2012 13:24:50)_

<b>What steps will reproduce the problem?</b>
1. apt-get install gradle   # on Ubuntu 11.10 oneiric
2. follow the steps for creating a new package on the rosjava &quot;Getting Started&quot; page
3. gradle build

<b>What is the expected output? What do you see instead?</b>

$ gradle build

A problem occurred evaluating root project 'test_java_core'.
Cause: Could not find method maven() for arguments [build_qrpk3gb7vg4fn9nn26dq7oqkj$_run_closure1_closure3@11eea7f0] on root project 'test_java_core'.

<b>What version of the product are you using? On what operating system?</b>

Ubuntu Oneiric 11.10, current rosjava_core tip

<b>Please provide any additional information below.</b>
- problem occurs in Gradle 1.0-milestone-3
- works with rosjava-bundled version (Gradle 1.0-milestone-9)

fix: put rosjava_core/gradlew as &quot;gradle&quot; onto your $PATH

I think this issue is rather a &quot;documentation bug&quot;: the Getting Started page should include information on how to use rosjava's gradle version.

also see: http://answers.ros.org/question/46961/error-in-building-new-package-in-rosjava_core/?answer=47074

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=149_

**Comment by damonkohler** [comment]
I think this has been addressed with the latest documentation.
