### ISSUE TITLE
Patch for /rosjava/src/main/java/org/ros/address/InetAddressFactory.java

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#150]
_Original author: markus.b...@gmail.com (November 06, 2012 14:27:00)_

Added check in newNonLoopback() to return the wlan ip4 address if wlan and point-to-point modem are present and have an ip4 address or return the point-to-point address if wlan is not active.
This is usefull if you use an smartphone or tablet with modem and wlan.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=150_

**Comment by chadrockey** [comment]
_From markus.b...@gmail.com on November 06, 2012 14:46:37_
Same issue as http://code.google.com/p/rosjava/issues/detail?id=147.
Please close both if this patch gets accepted.
Thank you.

Markus

**Comment by drigz** [comment]
Closing as this patch got lost in the transfer to GitHub, and it sounds like it's not the right solution to the problem - see discussion in https://github.com/rosjava/android_core/issues/147
