### ISSUE TITLE
Sourced maven repository no longer available

### ISSUE THREAD

**Issue by tfoote** [rosjava/rosjava_core#153]
The maven repository sourced in the rosjava distribution (robotbrains.hideho.org) seems to be no longer available (at least it has been down since yesterday now).

FWIW, replacing it with the following two repositories worked for my installation:
url 'https://maven.alfresco.com/nexus/content/repositories/public'
url 'https://maven-us.nuxeo.org/nexus/content/groups/public'

I don't know if those repositories are guaranteed to stay available for a longer period of time, though.

From  https://code.ros.org/trac/ros/ticket/4044

**Comment by damonkohler** [comment]
The custom repo that's defined in rosjava_core and android_core provides OSGi bundled JARs for some dependencies. These aren't currently required to build. But, they will be in the future.

In the meantime, the preferred work around for when that repo goes down is to use the mavenCentral() method to pull from Maven Central.

Another option would be to start a ROS Maven Repo. But that's outside the scope of this issue.
