### ISSUE TITLE
rosjava_jni does not log java exceptions

### ISSUE THREAD

**Issue by tfoote** [rosjava/rosjava_core#154]
Today I had a rather trivial problem with json_prolog buttracking it down was unnecessarily hard because the appropriate Java exception was nowhere to be seen.

Looking at rosjava_jni/rosjava.cpp, the handling function (dieOnException) simply prints the exception information with env->ExceptionDescribe(). According to documentation, this should print to stdout but apparently that has been silenced or redirected as the module - started directly or through rosrun - did not provide relevant debug output:

{{{
...
[DEBUG] [1346432157.547619948]: Making query from json object: [{"term":["owl_has", "http://ias.cs.tum.edu/kb/knowrob.owl#Drawer1", {"variable":"P"}, {"variable":"O"} ]}]  
[FATAL] [1346432157.565004562]: ASSERTION FAILED
    file = /home/bedahr/ros/client_rosjava_jni/rosjava_jni/rosjava.cpp
    line = 986
    cond = jresponse != 0 && dieOnException(env)

/home/bedahr/ros/json_prolog/bin/json_prolog: Zeile 14: 15295 Trace/Breakpoint ausgelöst   LD_PRELOAD=/usr/lib/libpl.so:$LIBJSIGL:$LD_PRELOAD LD_LIBRARY_PATH=/home/bedahr/ros/client_rosjava_jni/rosjava_jni/bin:/home/bedahr/ros/client_rosjava_jni/rosjava_jni/bin:/home/bedahr/ros/stacks/knowrob/3rdparty/jpl/jpl:/home/bedahr/ros/stacks/knowrob/3rdparty/jpl/prolog:$LD_LIBRARY_PATH java -classpath /home/bedahr/ros/json_prolog/bin:/home/bedahr/ros/json_prolog/bin:/home/bedahr/ros/client_rosjava_jni/rosjava_jni/bin:/home/bedahr/ros/stacks/knowrob/3rdparty/jpl/jpl/jpl.jar:/home/bedahr/ros/stacks/knowrob/3rdparty/jpl/prolog/jpl.jar:/usr/share/java/json-lib.jar:/home/bedahr/ros/client_rosjava_jni/rosjava_jni/bin::$CLASSPATH edu.tum.cs.ias.knowrob.json_prolog.JSONPrologNode $@

}}}

In my opinion, java exceptions should instead be published to rosout with an appropriate logging level (Error / Fatal).

From: https://code.ros.org/trac/ros/ticket/4041

**Comment by damonkohler** [comment]
This issue should be filed against rosjava_jni, not rosjava_core.
