### ISSUE TITLE
rosjava Tutorials broken 

### ISSUE THREAD

**Issue by tkruse** [rosjava/rosjava_core#178]
Hi, 

it seems that the rosjava infrastructure is changing to be guthub based, favoring a combination of catkin and gradle over pure gradle.

However it seems this move is not announced in any of the rosjava sites, and tutorials brake. I't suggest putting announcements in the first google results that come up when you google "rosjava tutorial", and point to new tutorials.
Also I believe it would be nice if the github rosjava organisation also had a rosjava_tutorials package, which could be an updated fork of
https://github.com/tkruse/rosjava_wiki_tutorials

**Comment by tkruse** [comment]
E.g. following the tutorial here:
http://docs.rosjava.googlecode.com/hg/rosjava_core/html/getting_started.html#creating-a-new-java-package

Gives me:
Could not resolve all dependencies for configuration ':compile'.

> Could not find ros.rosjava_core:rosjava:0.0.0-SNAPSHOT.

because that dependency seems to have been removed from http://robotbrains.hideho.org/nexus/content/groups/ros-public

**Comment by jvitku** [comment]
I agree that some demos are broken. In this case, the version of rosjava_core has been changed to newer version, from the build.gradle of rosjava_core

```
allprojects {
    group 'org.ros.rosjava_core'
    version = project.catkin.pkg.version
}
```

I assume that some catking plugin is parsing the current version from the package.xml: 

```
<?xml version="1.0"?>
<package>
  <name>rosjava_core</name>
  <version>0.1.3</version>
```

So changing the rosjava_core version in the dependency could temporarily solve your error.

**Comment by tkruse** [comment]
So... The whole purpose of having version numbers in general is that if there is a new version, the old version does not just vanish.
In this case, somebody removed the old version from http://robotbrains.hideho.org/nexus/content/groups/ros-public, so all packages in the world that relied on this are as of now broken. That in itself is not nice.

My guess would be that @damonkohler would know why that was done.

Now even with any other version number, I will not get anything from http://robotbrains.hideho.org/nexus/content/groups/ros-public, because no such packages are installed in the ros/rosjava-core hierarchy (nor is rosjava_core within the org.ros hierarchy). So it is not a matter of version numbers. The actual fix is to remove the reference to http://robotbrains.hideho.org/nexus/content/groups/ros-public, and instead add the reference to github, e.g.:

```
// enable to look up the ros-java gradle plugin and rosjava dependencies
buildscript {
    def rosMavenPath = "$System.env.ROS_MAVEN_PATH".split(':').collect { 'file://' + it }
    repositories {
        rosMavenPath.each { p ->
            maven {
                url p
            }
        }
        mavenLocal()
       maven {
            url 'https://github.com/rosjava/rosjava_mvn_repo/raw/master'
        }
    }
    dependencies {
        classpath group: 'org.ros.rosjava_bootstrap', name: 'gradle_plugins', version: '0.1.+'
   }
}

apply plugin: 'ros-java'
```

and then it is possible to use the new version / namespace:

```
dependencies {
  compile 'org.ros.rosjava_core:rosjava:0.1.+'
  compile 'org.ros.rosjava_messages:sensor_msgs:1.10.+'
}
```

Which, sadly, does not include version 0.0.0:

https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_core/rosjava

**Comment by damonkohler** [comment]
The use of the robotbrains repo was an unfortunate necessity a long time
ago. I don't think there is anything that depends on it now and it can
safely be replaced with mavenCentral. I'll put together a PR for the fix.

On Sat, Oct 19, 2013 at 12:46 PM, tkruse notifications@github.com wrote:

> So... The whole purpose of having version numbers in general is that if
> there is a new version, the old version does not just vanish.
> In this case, somebody removed the old version from
> http://robotbrains.hideho.org/nexus/content/groups/ros-public, so all
> packages in the world that relied on this are as of now broken. That in
> itself is not nice.
> 
> My guess would be that @damonkohler https://github.com/damonkohlerwould know why that was done.
> 
> Now even with any other version number, I will not get anything from
> http://robotbrains.hideho.org/nexus/content/groups/ros-public, because no
> such packages are installed in the ros/rosjava-core hierarchy. So it is not
> a matter of version numbers. The actual fix is to remove the reference to
> http://robotbrains.hideho.org/nexus/content/groups/ros-public, and
> instead add the reference to github, e.g.:
> 
> // enable to look up the ros-java gradle plugin and rosjava dependencies
> buildscript {
>     def rosMavenPath = "$System.env.ROS_MAVEN_PATH".split(':').collect { 'file://' + it }
>     repositories {
>         rosMavenPath.each { p ->
>             maven {
>                 url p
>             }
>         }
>         mavenLocal()
>        maven {
>             url 'https://github.com/rosjava/rosjava_mvn_repo/raw/master'
>         }
>     }
>     dependencies {
>         classpath group: 'org.ros.rosjava_bootstrap', name: 'gradle_plugins', version: '0.1.+'
>    }
> }
> 
> apply plugin: 'ros-java'
> 
> and then it is possible to use the new version / namespace:
> 
> dependencies {
>   compile 'org.ros.rosjava_core:rosjava:0.1.+'
>   compile 'org.ros.rosjava_messages:sensor_msgs:1.10.+'
> }
> 
> Which, sadly, does not include version 0.0.0:
> 
> https://github.com/rosjava/rosjava_mvn_repo/tree/master/org/ros/rosjava_core/rosjava
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rosjava/rosjava_core/issues/178#issuecomment-26647793
> .

## 

http://www.damonkohler.com/

**Comment by stonier** [comment]
I've mentioned this here: https://github.com/rosjava/rosjava_mvn_repo/issues/10

There's quite a few 3rd party dependencies coming from our rosjava maven repo (previously robotbrains). I haven't done any testing with regards to removing them and just depending on maven central counterparts, but I suspect there'll be a hiccup or two. It should be tested thoroughly first.

**Comment by stonier** [comment]
There has been plenty of announcements, not sure how you managed to miss them all. The wiki pages for a start point to new documentation, a rosjava sig was announced...

**Comment by tkruse** [comment]
@stonier : not sure whether you were talking to me. I generally did not follow rosjava news. I just saw the only tutorial that comes up when googling "rosjava tutorial" is broken because it requires rosjava packages which at this time are neither available at robotbrains nor maven central, as far as i can tell, and on that tutorial page there is no link to updated information.

The page https://code.google.com/p/rosjava/, which comes as a first result when googling "rosjava" does not mention any move to github, nor does it link to the wiki pointing to github. Maybe there have been useful announcements at other places, but for anyone starting rosjava today, that does not help.

The roswiki page that's supposed to have an updated build.gradle file just says "TODO":
http://wiki.ros.org/rosjava/Anatomy%20of%20a%20RosJava%20Package

So the old documentation does not work anymore while new documentation is neither complete, nor linked to from the old documentation. That's all I am saying.

**Comment by stonier** [comment]
Thanks for the feedback Thibault.

Yeah, some of the wiki pages have TODO's while the api is stabilising (close now). It is minor, but I've redirected to people where they can get useful information before those TODO's get fleshed out.

The google code frontpage could definitely use a redirector to the github site and docs. @damonkohler would you like to update that?

As for google hits, hard to manage that :P Not sure any of us have the manpower to ensure that the top google hits are going to the right place. For now we've got alot of redirections starting to go to the right places so hopefully the maze of rosjava information is getting simpler.

**Comment by stonier** [comment]
Closing this one. Reopen it if necessary.
