### ISSUE TITLE
Compiling rosjava_core Hydro branch failed.

### ISSUE THREAD

**Issue by posilva** [rosjava/rosjava_core#186]
Hi,

I'am trying to follow the guide(http://rosjava.github.io/rosjava_core/latest/) to install rosjava_core on my box.

But when I run './gradlew install  --info' I keep having this error: https://gist.github.com/posilva/7776911

For me the relevant error is: 

Resource missing. [HTTP GET: http://repo1.maven.org/maven2/org/apache/commons/com.springsource.org.apache.commons.httpclient/3.1.0/com.springsource.org.apache.commons.httpclient-3.1.0.pom]

I changed my build.gradle to this: https://gist.github.com/posilva/7776947
because repo1.maven2.org is missing the artifact.

Thanks for any help

**Comment by stonier** [comment]
Looks like the maven repository is not getting set. Doing this should fix it:

```
export ROS_MAVEN_REPOSITORY=https://github.com/rosjava/rosjava_mvn_repo/raw/master
```

That's supposed to get detected and set in this situation, I'll get to fixing that.

**Comment by stonier** [comment]
Hydro support is in - this should now work as expected.

(Note: the linked pull requests are for the changes merging into master, not hydro).
