### ISSUE TITLE
Build Issue Can't Find RawMessage

### ISSUE THREAD

**Issue by jheck88** [rosjava/rosjava_core#217]
Hi guy's I'm working on building the projects but I don't have a RawMessage.java to extend. Help?

**Comment by drigz** [comment]
This was probably an issue with how the build was invoked, as I was able to build without seeing this issue.

If anyone else runs in to it (or @sinisterrook, if you're still seeing it), reopen the issue and post the following information:

- OS type and version
- version of rosjava repositories being used and how they were checked out
- the commands used to build rosjava
- the exact error message
