### ISSUE TITLE
Support for ROS kinetic

### ISSUE THREAD

**Issue by talregev** [rosjava/rosjava_core#222]
Will rosjava support for ROS kinetic?

**Comment by Theosakamg** [comment]
I proposing my help

**Comment by vkuehn** [comment]
me too

**Comment by hippomormor** [comment]
Follow https://github.com/hippomormor/rosjava/blob/readme/README
Forked Android_core, Extras, Interactions, rosjava etc. for ROS Kinetic. 
Seems to be working with Android Studio  2.2 and SDK 23. Made for use by myself for a school project. Can't say if everything is working, but it seems OK so far.

**Comment by adamantivm** [comment]
Released! See: https://discourse.ros.org/t/rosjava-available-for-kinetic-kame/1070/3
