### ISSUE TITLE
Android Things

### ISSUE THREAD

**Issue by beriberikix** [rosjava/rosjava_core#230]
https://developer.android.com/things/

Has anyone tried running on Android Things?

**Comment by adamantivm** [comment]
Interesting question. I don't know of anyone but it looks very interesting! I would be interested to help support it.

Would you mind re-posting this question in the [rosjava discussion list](https://discourse.ros.org/c/rosjava) for a wider reach?

**Comment by beriberikix** [comment]
https://discourse.ros.org/t/android-things/1188 Done!

**Comment by adamantivm** [comment]
thanks a bunch
