### ISSUE TITLE
DefaultPublisher Leaks DefaultNode

### ISSUE THREAD

**Issue by stratomda** [rosjava/rosjava_core#237]
The DefaultPublisher class leaks the owning DefaultNode class. The corresponding TCP connection managers are also left open and are unable to be garbage collected.  The fix is to shutdown the listeners in the DefaultPublisher and remove the publishers and subscribers from the DefaultNode's topicParticipantManager.

**Comment by adamantivm** [comment]
Thanks for this analysis @stratomda . Do you think you'll be submitting a fix for this as well?

**Comment by stratomda** [comment]
@adamantivm I have fixed this and tested in indigo. I will update in the kinetic branch for ease of merging the pull request.

**Comment by adamantivm** [comment]
sounds great. Thank you very much!

**Comment by jubeira** [comment]
@adamantivm perhaps this could be cherrypicked to Indigo as well right?

**Comment by adamantivm** [comment]
absolutely.
