### ISSUE TITLE
package org.ros.message.rosgraph_msgs does not exist (diamondback)

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#28]
_Original author: pierrick...@gmail.com (August 25, 2011 08:47:44)_

Does rosjava still support Diamondback (on Ubuntu 11.04) ?

<b>What steps will reproduce the problem?</b>
rosinstall . /opt/ros/diamondback  http://rosjava.googlecode.com/hg/rosjava.rosinstall

rosmake rosjava

<b>What is the expected output? What do you see instead?</b>
rosmake fine

<b>What version of the product are you using? On what operating system?</b>
rosmake errors

<b>Please provide any additional information below.</b>

[rosmake-2] Starting &gt;&gt;&gt; rosjava [ make ]  
[ rosmake ] Last 40 linessjava: 6.0 sec ]                                                    [ 1 Active 51/54 Complete ]
{-------------------------------------------------------------------------------
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/message/new_style/MessageImpl.java:409: cannot find symbol
      [javac] symbol  : class Char
      [javac] location: class org.ros.internal.message.new_style.MessageImpl
      [javac]   public List&lt;Char&gt; getCharList(String name) {
      [javac]               ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/message/new_style/PrimitiveFieldType.java:24: package org.ros.message.std_msgs does not exist
      [javac] import org.ros.message.std_msgs.Char;
      [javac]                                ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/RosoutLogger.java:37: package org.ros.message.rosgraph_msgs does not exist
      [javac]   private final Publisher&lt;org.ros.message.rosgraph_msgs.Log&gt; publisher;
      [javac]                                                        ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/RosoutLogger.java:40: package org.ros.message.rosgraph_msgs does not exist
      [javac]   RosoutLogger(Log log, Publisher&lt;org.ros.message.rosgraph_msgs.Log&gt; publisher,
      [javac]                                                                ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/RosoutLogger.java:48: package org.ros.message.rosgraph_msgs does not exist
      [javac]   Publisher&lt;org.ros.message.rosgraph_msgs.Log&gt; getPublisher() {
      [javac]                                          ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/message/new_style/PrimitiveFieldType.java:90: cannot find symbol
      [javac] symbol: class Char
      [javac]       Preconditions.checkArgument(value instanceof Char);
      [javac]                                                    ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/DefaultNode.java:139: package org.ros.message.rosgraph_msgs does not exist
      [javac]     Publisher&lt;org.ros.message.rosgraph_msgs.Log&gt; rosoutPublisher =
      [javac]                                            ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/RosoutLogger.java:59: package org.ros.message.rosgraph_msgs does not exist
      [javac]     org.ros.message.rosgraph_msgs.Log m = new org.ros.message.rosgraph_msgs.Log();
      [javac]                                  ^
      [javac] /home/pierriko/work/ros-addons/rosjava_core/rosjava/src/main/java/org/ros/internal/node/RosoutLogger.java:59: package org.ros.message.rosgraph_msgs does not exist
      [javac]     org.ros.message.rosgraph_msgs.Log m = new org.ros.message.rosgraph_msgs.Log();
      [javac]                                                                            ^
      [javac] Note: Some input files use unchecked or unsafe operations.
      [javac] Note: Recompile with -Xlint:unchecked for details.
      [javac] 14 errors

  BUILD FAILED
  /home/pierriko/work/ros-addons/rosjava_core/rosjava/build.xml:43: Compile failed; see the compiler error output for details.

  Total time: 3 seconds
  Executing command: ['ant']
-------------------------------------------------------------------------------}
[ rosmake ] Output from build of package rosjava written to:
[ rosmake ]    /home/pierriko/.ros/rosmake/rosmake_output-20110825-153537/rosjava/build_output.log
[rosmake-2] Finished &lt;&lt;&lt; rosjava [FAIL] [ 6.08 seconds ]  
[ rosmake ] Halting due to failure in package rosjava. 

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=28_

**Comment by chadrockey** [comment]
_From pierrick...@gmail.com on August 29, 2011 03:34:20_
It seems that rosjava is using lib in ~/.ros/rosjava/lib/ , which were not up to date.
I deleted the ~/.ros folder, re-rosmake, which apparently fixed the issue.

**Comment by chadrockey** [comment]
_From andy.som...@gmail.com on October 20, 2011 16:05:59_
IMO while pierrick's solution of removing the ~/.ros directory works, this is still a bug. Build artifacts that can break a build should not be able to hang around in '.ros' if they are not explicitly installed.

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on March 13, 2012 09:45:10_
This should no longer be an issue with the new build system. See: http://docs.rosjava.googlecode.com/hg/html/index.html

**Comment by yeison** [comment]
Also, try this: 

Config changed, remember to run **'rosws update rosjava_core'** to update the folder from git
