### ISSUE TITLE
readme > https://discourse.ros.org/c/rosjava > "Oops! that page doesn't exist."

### ISSUE THREAD

**Issue by i-make-robots** [rosjava/rosjava_core#305]
Hello,

I've been tinkering with robot stuff for ages.  I'd like to talk to someone to explore if ROSjava is ready for my machines and vice versa.
The discussion link in the readme is broken.

Thanks,

**Comment by i-make-robots** [comment]
should point to https://discourse.ros.org/c/client-libraries/rosjava/5

**Comment by jorgenfb** [comment]
ROSJava is a dead project. I would suggest using one of the officially supported languages.

**Comment by i-make-robots** [comment]
please put that at the top of the readme.  ...and maybe archive this project.

Thanks!
