### ISSUE TITLE
Main function for service and client

### ISSUE THREAD

**Issue by ariharasudhanm** [rosjava/rosjava_core#307]
I am new to java, in the service client implementation I cannot find the main function to run both the server and client. Where can I find it or do someone already implemented if yes could you be kind enough to share it?

**Comment by SpyrosKou** [comment]
Hi @ariharasudhanm, 
there is an example of  [ros services](https://github.com/rosjava/rosjava_core/tree/kinetic/rosjava_tutorial_services) in this repository.

I have also created an example of starting both a ROS Service Server node and a ROS Service Client node from the same `main` function in pure java [here](https://github.com/SpyrosKou/Plain-ROS-Java-System-Example).
In the same example a ROS Topic Publisher and ROS Topic Subscriber are demonstrated.

**Comment by ariharasudhanm** [comment]
It worked, Thank you.
