### ISSUE TITLE
Add battery level indicator in UI

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#35]
_Original author: rhick...@google.com (September 09, 2011 19:03:40)_

To eliminate the need for running a workstation with the control panel we need to put support for those commands in the Android UI. This issue is specific to the power level indicator for monitoring batter life of the Create and netbook.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=35_

**Comment by jubeira** [comment]
This is already done in Android Remocons (see dashboard component [here](https://github.com/rosjava/android_remocons/blob/57af51faaa36e6344cf0233737b1dce4dd6d2ef9/common_tools/src/main/java/com/github/rosjava/android_remocons/common_tools/dashboards/DefaultDashboard.java)).
