### ISSUE TITLE
No Way to Set Message Queue Size on Subscriber

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#69]
_Original author: ei...@willowgarage.com (October 26, 2011 19:10:57)_

I have a problem where there are a lot of compressed messages coming into my rosjava application, but I only care about decompressing the latest message. As such, I want to set the size of my subscriber queue to 1. However, there is no way to do this in rosjava 
as the queue size is hard-coded in src/main/java/org/ros/internal/transport/IncomingMessageQueue.java line 36:

private static final int MESSAGE_BUFFER_CAPACITY = 8192;

There is also, to my knowledge, no way to determine how many messages are left in the queue in order to decide whether to process a message or move on to the latest one. This, in turn, means that my node falls woefully behind in processing messages.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=69_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on November 07, 2011 09:04:27_
Sounds like a good idea to me.

**Comment by MallikarjunTirlapur** [comment]
Hey chadrockey, whats the idea?
