### ISSUE TITLE
roslaunch uses XML-RPC function system.multicall - which is not supported by rosjava

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#84]
_Original author: matthewb...@gmail.com (January 31, 2012 18:03:47)_

<b>What steps will reproduce the problem?</b>
1. Run a roscore using rosjava on a machine running Windows 7
2. Aim a Linux based ROS install at the Windows roscore using ROS_MASTER_URI
3. Run a roslaunch launch-file on the Linux machine

<b>What is the expected output? What do you see instead?</b>

The expectation was that the nodes would be launched from the launch file. This failed, and the output was:

setting /run_id to dcbe8896-4c34-11e1-94e2-848f69afe3b2
process[rosout-1]: started with pid [15337]
started core service [/rosout]
load_parameters: unable to set parameters (last param was [None]): &lt;Fault 0: 'No such handler: system.multicall'&gt;
Traceback (most recent call last):
  File &quot;/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/**init**.py&quot;, line 252, in main
    p.start()
  File &quot;/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/parent.py&quot;, line 265, in start
    self.runner.launch()
  File &quot;/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/launch.py&quot;, line 644, in launch
    self._setup()
  File &quot;/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/launch.py&quot;, line 631, in _setup
    self._load_parameters()
  File &quot;/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/launch.py&quot;, line 311, in _load_parameters
    r = param_server_multi()
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 997, in __call__
    return MultiCallIterator(self.**server.system.multicall(marshalled_list))
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 1224, in __call**
    return self.__send(self.__name, args)
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 1575, in __request
    verbose=self.__verbose
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 1297, in single_request
    return self.parse_response(response)
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 1473, in parse_response
    return u.close()
  File &quot;/usr/lib/python2.7/xmlrpclib.py&quot;, line 793, in close
    raise Fault(**self._stack[0])
Fault: &lt;Fault 0: 'No such handler: system.multicall'&gt;
[rosout-1] killing on exit

<b>What version of the product are you using? On what operating system?</b>

The current head release, compiled under Ubuntu 11.10 and executed on a JVM running on Windows 7.

<b>Please provide any additional information below.</b>

The output indicates that roslaunch requires an implementation of the 'multicall' function to run properly. Running nodes individually outside of the launch file works as expected.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=84_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on January 31, 2012 18:23:58_
It looks like there is support for this in ws-xmlrpc. But, it needs to be set up correctly.

**Comment by chadrockey** [comment]
_From jkramert...@gmail.com on April 18, 2012 14:30:30_
From what I see -- and I note that this is the first time I've looked at the xmlrpc package -- multicall functionality isn't incorporated into the java version of xmlrpc v.3. I've modified XmlRpcStreamServer.java to handle it, found in the attached diff.

**Comment by Brassrat** [comment]
No diff attached, any chance of seeing it? or info about where you found it?

**Comment by jubeira** [comment]
Fixed via #273
